export type HelpType = "requests_help" | "offers_help";

export interface NGO {
  id: string;
  ngoName: string;
  projectName: string;
  description: string;
  impact: string;
  sdgTags: number[];
  location: string;
  helpType: HelpType;
  helpDetails: string;
  volunteerOpenings: number;
  category: string;
  status: "active" | "upcoming";
}

export const NGO_DATA: NGO[] = [
  {
    id: "anandam",
    ngoName: "Anandam NGO",
    projectName: "Free Old Age Home & Care",
    description: "Provides shelter, food, clothing, and medical support for abandoned senior citizens. Focuses on emotional well-being and dignity of the elderly.",
    impact: "Reduces elderly homelessness and improves quality of life for senior citizens across Tamil Nadu.",
    sdgTags: [1, 3, 10],
    location: "Chennai, Tamil Nadu",
    helpType: "requests_help",
    helpDetails: "Needs volunteers for daily care, medical camp support, and emotional counselling. Also seeking donations of food, clothing, and medicines.",
    volunteerOpenings: 12,
    category: "Elder Care",
    status: "active",
  },
  {
    id: "seyall",
    ngoName: "Seyall NGO",
    projectName: "Women Skill Development Program",
    description: "Trains women in tailoring, handicrafts, and entrepreneurship skills. Helps them become financially independent and start micro-enterprises.",
    impact: "Women empowerment and improved family income across rural Tamil Nadu.",
    sdgTags: [5, 8, 10],
    location: "Coimbatore, Tamil Nadu",
    helpType: "offers_help",
    helpDetails: "Offers free skill training in tailoring, handicrafts, and business basics. Can partner with NGOs serving rural women. Provides training materials and certified instructors.",
    volunteerOpenings: 0,
    category: "Women Empowerment",
    status: "active",
  },
  {
    id: "otrumai",
    ngoName: "Otrumai NGO",
    projectName: "Community Support & Food Drives",
    description: "Organizes food distribution and social service activities. Encourages youth volunteers to serve marginalized communities.",
    impact: "Hunger relief and stronger community unity in urban slums and rural areas.",
    sdgTags: [2, 11, 17],
    location: "Madurai, Tamil Nadu",
    helpType: "requests_help",
    helpDetails: "Urgently needs food drive coordinators, vehicle support, and volunteers for monthly distribution events. Seeking partnerships with local businesses and restaurants.",
    volunteerOpenings: 20,
    category: "Food Security",
    status: "active",
  },
  {
    id: "panchayat",
    ngoName: "Panchayat Learning Center NGO",
    projectName: "Rural Learning Centers",
    description: "Provides after-school education, basic literacy, and mentorship in villages. Builds confidence and academic foundation for first-generation learners.",
    impact: "Reduces school dropouts and improves education access for 2000+ rural children.",
    sdgTags: [4, 10, 17],
    location: "Vellore, Tamil Nadu",
    helpType: "offers_help",
    helpDetails: "Offers educational mentorship partnerships, curriculum support, and trained local teaching staff to sister NGOs. Can set up satellite centers in nearby villages.",
    volunteerOpenings: 0,
    category: "Education",
    status: "active",
  },
  {
    id: "thuvakkam",
    ngoName: "Thuvakkam NGO",
    projectName: "Blue Zone – Water Body Restoration",
    description: "Restores lakes and ponds, promotes rainwater conservation, and organizes community lake cleanup drives.",
    impact: "Improves groundwater levels and environmental sustainability in drought-prone districts.",
    sdgTags: [6, 13, 15],
    location: "Tirupur, Tamil Nadu",
    helpType: "requests_help",
    helpDetails: "Needs lake cleanup volunteers, environmental engineers, and support for geo-fencing surveys. Seeking grants and machinery for desilting operations.",
    volunteerOpenings: 30,
    category: "Environment",
    status: "active",
  },
  {
    id: "littleheart",
    ngoName: "Little Heart NGO",
    projectName: "Child Welfare & Education Support",
    description: "Provides food, school supplies, and healthcare access for underprivileged children in urban slums and rural villages.",
    impact: "Better education access and holistic child development for 800+ children.",
    sdgTags: [2, 3, 4],
    location: "Salem, Tamil Nadu",
    helpType: "requests_help",
    helpDetails: "Needs teaching volunteers (weekends), healthcare professionals for monthly camps, and donations of school supplies and nutritious food items.",
    volunteerOpenings: 15,
    category: "Child Welfare",
    status: "active",
  },
  {
    id: "mohanvision",
    ngoName: "Mohan Vision NGO",
    projectName: "Free Eye Care Camps",
    description: "Conducts eye checkups in rural areas, provides prescription glasses for free, and supports cataract surgeries for patients who cannot afford treatment.",
    impact: "Prevents blindness and improves vision health for thousands of rural adults and elderly.",
    sdgTags: [3, 10],
    location: "Trichy, Tamil Nadu",
    helpType: "offers_help",
    helpDetails: "Offers free eye care camp partnerships to NGOs serving rural and tribal populations. Can provide ophthalmologists, equipment, and free glasses. Seeking transport and local coordination.",
    volunteerOpenings: 5,
    category: "Healthcare",
    status: "active",
  },
  {
    id: "goldenheart",
    ngoName: "Golden Heart NGO",
    projectName: "Hunger Relief Program",
    description: "Distributes nutritious meals daily to homeless individuals, construction workers, and low-income families in urban areas.",
    impact: "Reduces urban hunger and supports daily survival of 500+ people.",
    sdgTags: [1, 2, 11],
    location: "Chennai, Tamil Nadu",
    helpType: "requests_help",
    helpDetails: "Needs daily meal preparation volunteers, delivery logistics support, and regular food donations from restaurants, caterers, and individuals.",
    volunteerOpenings: 25,
    category: "Food Security",
    status: "active",
  },
  {
    id: "agaram",
    ngoName: "Agaram Foundation",
    projectName: "Higher Education Support Program",
    description: "Provides scholarships, mentoring, and career guidance for rural and first-generation college students to access quality higher education.",
    impact: "Increases access to higher education and career opportunities for 1000+ students annually.",
    sdgTags: [4, 8, 10],
    location: "Chennai, Tamil Nadu",
    helpType: "offers_help",
    helpDetails: "Offers scholarships, career counselling sessions, and mentoring partnerships to rural students and allied NGOs. Can conduct educational workshops and awareness drives.",
    volunteerOpenings: 10,
    category: "Education",
    status: "active",
  },
  {
    id: "tankers",
    ngoName: "Tankers Foundation",
    projectName: "Clean Water Supply Initiative",
    description: "Supplies clean drinking water to water-scarce areas through tankers and works on building permanent water supply infrastructure.",
    impact: "Improves public health and solves acute water shortages for 50,000+ people.",
    sdgTags: [6, 3, 1],
    location: "Chennai, Tamil Nadu",
    helpType: "requests_help",
    helpDetails: "Needs water distribution volunteers, infrastructure engineers, and community coordinators. Seeking partnerships with local authorities and funding for pipeline projects.",
    volunteerOpenings: 8,
    category: "Water & Sanitation",
    status: "active",
  },
  {
    id: "aaram",
    ngoName: "Aaram Foundation",
    projectName: "Women Empowerment Initiative",
    description: "Provides livelihood training, digital literacy, and employment placement opportunities to women from low-income households.",
    impact: "Economic independence for 2000+ women across Tamil Nadu.",
    sdgTags: [5, 8, 1],
    location: "Tirunelveli, Tamil Nadu",
    helpType: "offers_help",
    helpDetails: "Offers livelihood training, digital literacy programs, and job placement assistance. Available to partner with NGOs serving women in rural and semi-urban areas.",
    volunteerOpenings: 0,
    category: "Women Empowerment",
    status: "active",
  },
  {
    id: "ecosocieties",
    ngoName: "Eco Societies India NGO",
    projectName: "Environmental Awareness Programs",
    description: "Conducts tree planting drives, waste management awareness, and eco-education campaigns in schools and colleges across India.",
    impact: "Promotes sustainability culture and has planted 100,000+ trees.",
    sdgTags: [13, 15, 11],
    location: "Bangalore, Karnataka",
    helpType: "offers_help",
    helpDetails: "Offers environmental awareness workshops, tree planting event partnerships, and eco-campaign support to schools, colleges, and allied NGOs across South India.",
    volunteerOpenings: 0,
    category: "Environment",
    status: "active",
  },
  {
    id: "vidhigal",
    ngoName: "Vidhigal NGO",
    projectName: "Child Rights & Legal Awareness",
    description: "Conducts awareness programs on child safety, child rights, and legal procedures in schools, villages, and community centers.",
    impact: "Protects children and increases legal awareness for parents and educators.",
    sdgTags: [4, 16, 10],
    location: "Puducherry",
    helpType: "offers_help",
    helpDetails: "Offers free legal awareness workshops, child safety training, and rights education sessions. Can partner with schools, hostels, and NGOs serving children.",
    volunteerOpenings: 3,
    category: "Child Rights",
    status: "active",
  },
  {
    id: "bhumi",
    ngoName: "Bhumi NGO",
    projectName: "Ignite Education Program",
    description: "Volunteer-driven program where trained volunteers teach underprivileged children academics, life skills, and digital literacy on weekends.",
    impact: "Improves education quality and student confidence for 10,000+ children across India.",
    sdgTags: [4, 10, 17],
    location: "Chennai, Tamil Nadu",
    helpType: "requests_help",
    helpDetails: "Needs volunteer teachers for weekend sessions (English, Maths, Science, Digital Literacy). Also needs content designers and training coordinators.",
    volunteerOpenings: 50,
    category: "Education",
    status: "active",
  },
];
